import assert from 'node:assert/strict';
import {allComplete,defaultSettings,fresh,normalizeStream,quota,reduce,remaining,validateSettings} from '../lib/stream.ts';
let s=fresh('valorant'),seq=0;
const act=x=>{s=reduce(s,{id:`test-${++seq}`,...x});return s;};
assert.equal(s.settings.panels.length,6);
const custom=structuredClone(s.settings);
custom.pointLabel='pt';custom.pointsPerKill=250;
custom.panels=[{id:'kills',name:'キル達成',goal:3,unit:'回'},{id:'gifts',name:'ギフト目標',goal:4,unit:'個'}];
custom.gifts.small={name:'星',points:170,panelId:'gifts'};
custom.ranks=[{name:'低ランク',factor:.3},{name:'高ランク',factor:1.5}];
act({kind:'configure',settings:custom});
assert.equal(s.counts.panels.length,2);
act({kind:'gift',gift:'small',quantity:3});assert.equal(s.counts.bc,510);assert.equal(s.counts.panels[1],3);assert.equal(quota(s.counts,s.settings),2);
act({kind:'other',quantity:2,unitBC:120});assert.equal(s.counts.bc,750);assert.equal(quota(s.counts,s.settings),3);
act({kind:'kill',quantity:5,rank:.3,direction:1});assert.equal(s.counts.kills,5);assert.equal(s.counts.converted,1);assert.equal(remaining(s.counts,s.settings),2);
act({kind:'party',players:[{quantity:5,rank:.3},{quantity:3,rank:1.5},{quantity:1,rank:.3},{quantity:0,rank:1.5},{quantity:2,rank:1.5}]});
assert.equal(s.counts.kills,16);assert.equal(s.counts.converted,9);
act({kind:'panel',panelId:'kills',quantity:3,direction:1});act({kind:'panel',panelId:'gifts',quantity:1,direction:1});assert.equal(allComplete(s.counts,s.settings),true);
act({kind:'panel',panelId:'gifts',quantity:1,direction:-1});assert.equal(allComplete(s.counts,s.settings),false);
act({kind:'undo'});assert.equal(allComplete(s.counts,s.settings),true);
act({kind:'redo'});assert.equal(allComplete(s.counts,s.settings),false);
const before=s;assert.equal(reduce(s,{id:s.seen.at(-1),kind:'gift',gift:'small',quantity:1}),before);
assert.throws(()=>act({kind:'panel',panelId:'gifts',quantity:100,direction:-1}),/超えています/);
const edited=structuredClone(s.settings);edited.panels=[{...edited.panels[1],name:'新しい名前'},{id:'extra',name:'追加',goal:1,unit:'回'}];
act({kind:'configure',settings:edited});assert.deepEqual(s.counts.panels,[3,0]);assert.equal(s.undo.length,0);
assert.throws(()=>act({kind:'undo'}),/戻せる/);
assert.throws(()=>validateSettings({...edited,pointsPerKill:0}),/ポイント/);
const apex=fresh('apex');assert.equal(apex.settings.game,'apex');assert.equal(apex.settings.ranks.at(-1).name,'Apexプレデター');
assert.throws(()=>reduce(apex,{id:'wrong-team',kind:'party',players:Array(5).fill({quantity:1,rank:1})}),/3人/);
const apexNext=reduce(apex,{id:'apex-team',kind:'party',players:Array(3).fill({quantity:2,rank:1})});assert.equal(apexNext.counts.kills,6);assert.equal(apex.counts.kills,0);
let gifts=fresh('apex');
gifts=reduce(gifts,{id:'medium',kind:'gift',gift:'medium',quantity:2});
gifts=reduce(gifts,{id:'large',kind:'gift',gift:'large',quantity:1});
assert.equal(gifts.counts.bc,31000);assert.equal(quota(gifts.counts,gifts.settings),62);
gifts=reduce(gifts,{id:'undo-large',kind:'undo'});assert.equal(gifts.counts.bc,6000);
gifts=reduce(gifts,{id:'redo-large',kind:'redo'});assert.equal(gifts.counts.bc,31000);
gifts=reduce(gifts,{id:'reset-all',kind:'resetAll'});assert.equal(gifts.counts.bc,0);
gifts=reduce(gifts,{id:'undo-reset',kind:'undo'});assert.equal(gifts.counts.bc,31000);
const legacy=normalizeStream({counts:{bc:2499,kills:5,converted:3,panels:Array(8).fill(1)},undo:[],redo:[],seen:[],lastAction:''},'valorant');
assert.equal(legacy.settings.panels[0].name,'フルエール');assert.equal(legacy.counts.bc,2499);assert.equal(quota(legacy.counts,legacy.settings),4);
const imported=reduce({...fresh('valorant'),settings:legacy.settings,counts:{bc:0,kills:0,converted:0,panels:Array(8).fill(0)}},{id:'import',kind:'importLegacy',legacy:{bc:500,kills:2,panels:[1,2,3,4,5]}});
assert.deepEqual(imported.counts.panels,[1,2,0,3,4,0,0,0]);
console.log('PASS: custom points, panels, gifts, ranks, VALORANT/APEX teams, game separation, undo/redo, migration and validation');
